# Generated by Django 2.2.4 on 2019-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=64, null=True)),
                ('worker_processes', models.IntegerField()),
                ('worker_connections', models.IntegerField()),
                ('keepalive_timeout', models.IntegerField()),
                ('client_max_body_size', models.IntegerField()),
                ('access_log', models.CharField(max_length=128)),
                ('error_log', models.CharField(max_length=128, null=True)),
                ('update_time', models.FloatField()),
            ],
        ),
    ]
